## install diyabcGUI and dependencies (for Windows)
## to be run by R-Portable

# force update ?
force_update <- TRUE

message("---------------------------------------------------------------------")
message("Starting preparation")
message("---------------------------------------------------------------------")

## requirement: .Renviron file generated by 'generate_Renviron.R'
if(!file.exists(".Renviron"))
    stop("You should run 'generate_Renviron.R'")

# R lib
R_lib <- file.path("app", "library")
if(!dir.exists(R_lib)) dir.create(R_lib)

# requirement
pkg_list <- c("devtools", "jsonlite")
install_pkg(pkg_list, force_update, R_lib, type = "binary")

dep_list <- unname(unlist(read.table(
    file.path("app", "packages.txt"), header = FALSE, stringsAsFactors = FALSE
)))
install_pkg(dep_list, force_update, R_lib, type = "binary")

# install diyabcGUI from zip source
if(dir.exists(file.path(R_lib, "diyabcGUI")))
    fs::dir_delete(file.path(R_lib, "diyabcGUI"))
zip_src <- tail(sort(list.files("src", pattern = "diyabcGUI*")), 1)
install.packages(
    file.path("src", zip_src), repos = NULL, type = "win.binary", lib = R_lib
)

message("---------------------------------------------------------------------")
message("Preparation is done")
message("---------------------------------------------------------------------")

