## install diyabcGUI and dependencies (for Windows)
## to be run by R-Portable

message("---------------------------------------------------------------------")
message("Starting preparation")
message("---------------------------------------------------------------------")

## requirement: .Renviron file generated by 'generate_Renviron.R'
if(!file.exists(".Renviron"))
    stop("You should run 'generate_Renviron.R'")

# default CRAN repos
local({
    r <- getOption("repos")
    r["CRAN"] <- "https://cran.r-project.org"
    options(repos=r)
})

# R lib
R_lib <- file.path("app", "library")
if(!dir.exists(R_lib)) dir.create(R_lib)

# requirement
install.packages("devtools", lib = R_lib)
install.packages("jsonlite", lib = R_lib)
dep <- unlist(read.table(
    file.path("app", "packages.txt"), header = FALSE, stringsAsFactors = FALSE
))
install.packages(dep, lib = R_lib)

# local install from Rcpp
devtools::install(
    file.path("src", "Rcpp"), 
    args = c(paste0('--library="', '.', .Platform$file.sep, R_lib, '"'))
)

# install diyabcGUI from zip source
zip_src <- tail(sort(list.files("src", pattern = "diyabcGUI*")), 1)
install.packages(
    file.path("src", zip_src), repos = NULL, type = "win.binary", lib = R_lib
)

message("---------------------------------------------------------------------")
message("Preparation is done")
message("---------------------------------------------------------------------")

