## run app locally with R-Portable for debugging
## to be run by R-Portable

## requirement: .Renviron file generated by 'generate_Renviron.R'
if(!file.exists(".Renviron"))
    stop("You should run 'generate_Renviron.R'")

# default CRAN repos
local({
    r <- getOption("repos")
    r["CRAN"] <- "https://cran.r-project.org"
    options(repos=r)
})

# running the app
library(diyabcGUI)
enable_logging()
diyabc()
